### ISSUE TITLE
PRDT: Document Data Discoveries

### ISSUE THREAD

**Issue by Dianadec** [bcgov/reserve-rec-public#1]
#### Description:
Before prototyping, we need to explore and understand backcountry booking data, including where/how it is stored, scope/scale, any gaps, and begin exploring future storage/improvements.  

This ticket is to gain access to and look at available data for backcountry, and document potential gaps/unmet needs before moving forward.

#### Acceptance Criteria:

- [x] Attend tutorial from reservation services on backcountry admin/field system (Jun 25 1:30-2:30)
- [x] Dev team access to field system (In progress - Diana working with Jessica M)
- [ ] Review Camis attendance reports: (https://bcgov.sharepoint.com/:x:/r/teams/031072/_layouts/15/Doc.aspx?sourcedoc=%7BC1BE4FA2-C24C-4A38-9B82-94E5A0D46DAF%7D&file=BackcountryReg-StatReport-Daily-Mar-2022-Mar-2024-AllAccessPts.xlsx&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&action=default&mobileredirect=true
- [ ] Document data gaps, or missing data required to move forward (if any)
- [ ] Document future storage possibilities/ideas (if any)

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes
Notes from June 4 Refinement:
- We can get access to admin side, but API can't be shared.
- City Wide has a lot of data in that system
- Details on reservations, parks site, city wide, if one thing gets updated, how do we make sure it gets updated across all the things?
- Can we be the authoritative source of the data?
- Who are all the consumers of this data? We get media requests, other sites scrape the data to create their own notify systems for example.

**Comment by cameronpettit** [comment]
Documenting any and all data we will need for a jumping off point:

### Site Information
- [ ] All types of permits handled as part of MVP:
  - [ ] Backcountry Reservations (tent pads)
  - [ ] Backcountry Registration (unlimited people)
  - [ ] Backcountry Shelters (bunks)
  - [ ] Wilderness (limited people)
  - [ ] Canoe Circuit (canoes)
- [ ] All parks involved with all permits above (ie: Garibaldi)
- [ ] All subareas involved with all permits above (ie: Garibaldi - Cheakamus Lake)
  Relevant subarea metadata:
  - [ ] Geospatial (see #4)
  - [ ] Administrative region/section (see A&R)
  - [ ] timezone
- [ ] All permits belonging to each subarea (ie: Garibaldi - Cheakamus Lake - Backcountry Reservations)

### Inventory
- [ ] The inventory belonging to each specific permit (ie: Garibaldi - Cheakamus Lake - Backcountry Reservations = 8 tent pads)
  Relevant inventory metadata:
  - [ ] Geospatial (see #4)
  - [ ] Quantity per permit
  - [ ] Type (tent pads, bunks, etc)
  - [ ] Availability (finite or infinite)

### Booking Policies
- [ ] The booking policies associated with every permit
  Relevant booking policy information:
  - [ ] Minimum number of nights allowed per booking
  - [ ] Maximum number of nights allowed per calendar year
  - [ ] Reservation window type (launch date or rolling window)
    - [ ] If rolling window, the number of months prior to the date upon which a permit becomes bookable
    - [ ] If launch date, the date in question
  - [ ] The hour of day the permit will become available to book on the first day it becomes available (timezone factored in)
  - [ ] Whether or not the permit has a Restricted Booking Window, and the duration of the window if it exists
  - [ ] The check-in and check-out times of the permit
  - [ ] The time that no-show takes effect on the permit
  - [ ] Any other special booking policies

### Party Policies
- [ ] The party policies associated with every permit
  Relevant party policy information
  - [ ] The minimum age of the Named Occupant
  - [ ] The minimum and maximum allowable party size
  - [ ] The maximum number of people allowed per tent pad/bunk/canoe/etc
  - [ ] Vehicle information/restrictions, if applicable
  - [ ] Any other special party policies

### Change and Cancellation Policies
- [ ] The change/cancellation policies associated with every permit
  Relevant change and cancellation policy information
  - [ ] Whether or not changes/cancellations are permitted
  - [ ] The cancellation window, prior to which a full refund of base fees is given less cancellation fees.
  - [ ] The fees forfeit if cancelling/changing within the cancellation window
  - [ ] The fees forfeit if cancelling/changing on the date of arrival
  - [ ] Any other special change/cancellation policies
