### ISSUE TITLE
Design: User journeys for reservation system

### ISSUE THREAD

**Issue by meyerdarcie** [bcgov/reserve-rec-public#26]
#### Description:

This ticket is to create user journeys for the backcountry booking experience, to support program area feedback and exploration of business rules. 

#### Acceptance Criteria:

- [x] User journeys are created for backcountry, frontcountry, rec site, group, canoe circuit, trail and day use pass reservations
- [ ] User journey for backcountry includes preliminary sketches 
- [x] User journeys follows the figjam workflow and the user story map (linked below)
- [x] User journeys for everything but backcountry are kept at a conceptual, high-level

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Wireframe(s):**
[Figma - PRDT Sketches](https://www.figma.com/design/1QHd1cWiRqeC0Ua0E9nfhr/PRDT?node-id=201-956)

**Workflows:**
[Backcountry booking flow](https://www.figma.com/board/HNsft6y1lXjuGF2mh1Icv7/Backcountry-Booking-Flow?node-id=0-1&node-type=canvas&t=HprvJqvSG6r0tW2d-0)

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by meyerdarcie** [comment]
@pavelcreates FYI on user journeys ticket, I haven't added acceptance criteria yet, but we can chat more on this if you want to collaborate on it.

**Comment by pavelcreates** [comment]
@meyerdarcie made some adjustments - let me know what you think! 😄

**Comment by meyerdarcie** [comment]
Looks good @pavelcreates, I would caution against scope creep on this ticket if you're considering user journeys for all of the offerings over and above backcountry, but trust you to be able to judge that. If it does grow too big, then a focus on backcountry would be my recommendation for now, as we'll undoubtedly learn quite a bit from doing that one alone. There are so many one-off situations that this chunk of work in the acceptance criteria could grow pretty big - but I see that you added keeping them high level, so that is good. Thanks!

**Comment by pavelcreates** [comment]
Makes sense, my goal is to get a sense, at the high level, of how things would work as a system and only going into detail around backcountry. I am happy to reformat the ticket to only focus on backcountry, if that is best.

**Comment by pavelcreates** [comment]
User Story mural board: https://app.mural.co/t/bcparks2575/m/bcparks2575/1726680066512/5652b67d159072470ba2b8d8b85445394dc14cdc?sender=ufd2ca96aab5cb83946b14097

**Comment by LindsayMacfarlane** [comment]
Hi @pavelcreates - these all look fantastic! I'll move to done, but would love a walk through of everything when you're back from your amazing holidays. I looked at:

https://app.mural.co/t/bcparks2575/m/bcparks2575/1726680066512/5652b67d159072470ba2b8d8b85445394dc14cdc?sender=u45121c4ffd92ebc876901869 

https://www.figma.com/design/1QHd1cWiRqeC0Ua0E9nfhr/PRDT?node-id=201-956&node-type=canvas&t=0mHia8ZK2qf9BcUu-0

https://www.figma.com/board/HNsft6y1lXjuGF2mh1Icv7/Backcountry-Booking-Flow?node-id=0-1&node-type=canvas&t=sRMXLDQklg9rll0r-0
