### ISSUE TITLE
[L] Backcountry Frontend: Create service layer to pull data from opensearch

### ISSUE THREAD

**Issue by Dianadec** [bcgov/reserve-rec-public#28]
#### Description:

Early stages of front end - not based off designs - just to get something out there.

#### Acceptance Criteria:
- List of backcountry parks shows up in front-end in dev ("Approaching") - the list of ONLY BACKCOUNTRY parks in the environment.

#### Development Checklist:

- [ ] Angular service can facilitate fetching of data from our backend (developer can see this)
- [ ] Plumbing for the rest of the application to be aware of the data that's bein pulled in from this service layer
- [ ] Backcountry label or some kind of attribute assigned to parks to label them as backcountry.

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**
- 

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by manuji** [comment]
Tested on Dev: **Passed**
* verified that when searched for a keyword, the page shows list of parks matching the search keyword.
* Passing to PO review. 
 ![Image](https://github.com/user-attachments/assets/852e250a-a3e2-4a0e-9792-4580f9ddf543)

**Comment by LindsayMacfarlane** [comment]
Tested on Test. Passed. 

- Tested using key words (Champion, Lake, Park, Boat, Joffre). 

Thanks everyone for your work on this one!
