### ISSUE TITLE
Facilitating design co-design/validation workshops

### ISSUE THREAD

**Issue by Dianadec** [bcgov/reserve-rec-public#30]
#### Description:
Let's test and validate our designs! 

These sessions will be focused on internal users/staff to get feedback on initial designs. This will help us validate if we are on the right track and make any iterative changes before we start building out the frontend in more depth. 

#### Acceptance Criteria:
- [x] Co-design/validation workshops booked with Rec Services, A&R, Res Services, RST and Info Services
- [x] Workshop templates created on mural
- [x] Workshop script created

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by LindsayMacfarlane** [comment]
Hi @pavelcreates - can you please take a look at this ticket and refine if needed before Thursday's sprint planning. Thanks!

**Comment by pavelcreates** [comment]
Looks good to go! I made some edits to the ticket name, status and acceptance criteria as this is currently in progress.

**Comment by LindsayMacfarlane** [comment]
It's been so informative sitting in on these sessions @pavelcreates - looking forward to seeing the analysis and next steps from that.
