### ISSUE TITLE
Ability to click a pin on the map

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/reserve-rec-public#32]
#### Description:
Implement UI based on PAPER NAPKIN VERSION of designs that includes the ability to click a pin on the map to find more information about a park of interest.

#### User Story:
As a public user, I want to be able to click a link on a map to find out more information about a park I am interested in booking for backcountry camping. 

#### Acceptance Criteria:

Given I am a public user
When I search for a park on a map
Then I can select the pin to find out more information related to that park

- [ ] User interface created based off of  PAPER NAPKIN VERSION of designs.

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Wireframe(s):**
https://www.figma.com/design/1QHd1cWiRqeC0Ua0E9nfhr/PRDT?node-id=201-956&t=Z5YDTwcMDBcmb8dY-1

**Workflows:**

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by LindsayMacfarlane** [comment]
Mark recommends keeping this ticket. It isn't currently captured in the existing Maplibre work. 

cc: @Dianadec

**Comment by marklise** [comment]
@LindsayMacfarlane Yes! That's exactly right.

**Comment by LindsayMacfarlane** [comment]
Perfect! Thank you for your work on this ticket!
