### ISSUE TITLE
[L] PRDT: Explore Map technologies

### ISSUE THREAD

**Issue by Dianadec** [bcgov/reserve-rec-public#4]
#### Description:
Mapping is a priority for backcountry bookings - we know that 75% of users start by looking at a map when thinking about booking camping experiences. 

This ticket is to get up to speed on current mapping efforts within BC Parks, and determine what tool would be best for our MVP. 

#### Acceptance Criteria:

- [x] Meet with Rex to understand research/discovery that info services has completed to date
- [x] Scan existing technologies to explore what could be used for backcountry map
- [x] Based on outcomes of data exploration, document geospatial needs/considerations/blockers for implementation
- [x] Determine where are we getting the geospatial data from
  - CityWide, exported to file share SHP and KML datasets. Only spatial files.
  - CityWide API not appropriate for use
  - DB Direct connect available
  - bcgw not an option (on hold)
- [x] Recommendation on what mapping tool should be used for backcountry MVP
  - Mapbox seems to be the winner. Great tooling, documentation, etc.
- Geospatial data can be stored in Dynamo as GEOJSON
  - indexing on lat/lons can be done using geohash (see https://geohash.softeng.co/ as an example). Very performant and works well w.r.t. dynamo not supporting geospatial natively.  Libraries exist to create geohashes for shapes. Index size correlates to performance and granularity
  - see https://aws.amazon.com/blogs/mobile/geo-library-for-amazon-dynamodb-part-1-table-structure/ for practical example

#### Dependencies

- Blocked by none
- Blocking none

#### Notes:
- Options for mapping:
  - Leaflet
  - MapBox
  - arcgis

**Comment by Dianadec** [comment]
Planning notes:
- Biggest question - where are we getting the geospatial data from?

**Comment by marklise** [comment]
Question around geospatial - we have no authoritative data that we can reliably use.

**Comment by JLWade** [comment]
Couple thoughts:

- wonder if there is somewhere (like Strathcona Park) we could start with? If citywide has something and then perhaps comparing it to google earth and coming up with a couple backcountry entry points or camping locations as a first step. 
- we could use what is in citywide with some disclaimers that the data may not be 100% accurate
- given the potential inaccuracies in the data - can the tool be built in such a way that it is easy to change the location if needed? Especially if it is not to be released to the public right away, we could test it with what data is available and then change as we learn more?

**Comment by Dianadec** [comment]
Refinement notes: @marklise  to add info to these tickets:

- need to setup the next steps ticket: "Implement first cut of mapping tool"
- Info in geoserver in city wide - we don't want to query that - so need some kind of caching tool - so step one is to setup backend of mapping app
- second step = query ourselves, implement front-end that can render things

**Comment by marklise** [comment]
Cape scott test data:

Features
[bcparks.egis.citywidesolutions.com/geoserver/citywide_gis/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=citywide_gis%3Afurniture_ows&outputFormat=application%2Fjson&srs=EPSG:4326&CQL_FILTER=park=%27Cape Scott Park%27](https://bcparks.egis.citywidesolutions.com/geoserver/citywide_gis/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=citywide_gis%3Afurniture_ows&outputFormat=application%2Fjson&srs=EPSG:4326&CQL_FILTER=park=%27Cape%20Scott%20Park%27)

Grounds
[bcparks.egis.citywidesolutions.com/geoserver/citywide_gis/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=citywide_gis%3Agrounds_ows&outputFormat=application%2Fjson&CQL_FILTER=park=%27Cape Scott Park%27](https://bcparks.egis.citywidesolutions.com/geoserver/citywide_gis/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=citywide_gis%3Agrounds_ows&outputFormat=application%2Fjson&CQL_FILTER=park=%27Cape%20Scott%20Park%27)

Trails
[bcparks.egis.citywidesolutions.com/geoserver/citywide_gis/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=citywide_gis%3Atrails_ows&outputFormat=application%2Fjson&CQL_FILTER=park=%27Cape Scott Park%27](https://bcparks.egis.citywidesolutions.com/geoserver/citywide_gis/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=citywide_gis%3Atrails_ows&outputFormat=application%2Fjson&CQL_FILTER=park=%27Cape%20Scott%20Park%27)
