### ISSUE TITLE
Intro to backcountry

### ISSUE THREAD

**Issue by JLWade** [bcgov/reserve-rec-public#6]
#### Description:

Backcountry will be the first thing we can look at when thinking about enhancing a future reservation system.

#### Acceptance Criteria:

- [x] - determine initial approach on repository management
- [x] - determine initial approach on hosting set up
- [x] - Meet with reservation service team (may 1)
- [x] - Collect questions from team in advance of reservation service team meetup
- [ ] - continue wardley mapping to help with approach (could be related to repos?) (Jess + Diana)
- [x] - Create super basic flow (one goal of next sprint = want to prototype a payment component of that)
- [x] - Determine privacy protocols/confidentiality

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

#### Notes:
- 
-

**Comment by Dianadec** [comment]
@JLWade we're going to close this but will follow up with you about wardley mapping. cc @meyerdarcie
